// Base de dados de empresas do Guia Comercial AG5
// Arquivo separado para facilitar manutencao e atualizacoes
const companiesData = [
    { "id": 1, "name": "DJ Materiais", "category": "🧱 Loja de Materiais de Construção", "link": "https://g.co/kgs/giMaijZ", "keywords": ["DJ Materiais", "Loja de Materiais de Construção", "material de obra", "reforma", "construção", "casa"] },
    { "id": 2, "name": "PP Celulares", "category": "📱 Loja de Celulares", "link": "https://g.co/kgs/d7ECxLY", "keywords": ["PP Celulares", "Loja de Celulares", "celulares", "smartphone", "tecnologia", "eletrônicos"] },
    { "id": 3, "name": "Bellas Modas", "category": "👗 Loja de Roupas", "link": "N/A", "keywords": ["Bellas Modas", "Loja de Roupas", "moda", "vestuário", "roupa feminina", "tendências"] },
    { "id": 4, "name": "Moda Carioca", "category": "👕 Loja de Moda Masculina", "link": "N/A", "keywords": ["Moda Carioca", "Loja de Moda Masculina", "moda masculina", "vestuário", "roupa", "estilo"] },
    { "id": 5, "name": "Vera Modas Fashion - Moda Feminina", "category": "👚 Loja de Moda Feminina", "link": "N/A", "keywords": ["Vera Modas Fashion", "Loja de Moda Feminina", "moda feminina", "roupa", "vestuário", "tendências"] },
    { "id": 6, "name": "Vera Modas Kids", "category": "👶 Loja Infantil", "link": "N/A", "keywords": ["Vera Modas Kids", "Loja Infantil", "moda infantil", "roupa de criança", "artigos infantis", "brinquedos"] },
    { "id": 7, "name": "Daytona Auto Center", "category": "🚘 Oficina Mecânica", "link": "N/A", "keywords": ["Daytona Auto Center", "Oficina Mecânica", "mecânica automotiva", "manutenção veicular", "serviços automotivos", "carro"] },
    { "id": 8, "name": "Angel Feet Calçados", "category": "👟 Loja de Calçados", "link": "N/A", "keywords": ["Angel Feet Calçados", "Loja de Calçados", "sapatos", "tênis", "moda calçados", "conforto"] },
    { "id": 9, "name": "Ótica Boa Visão", "category": "👓 Ótica", "link": "N/A", "keywords": ["Ótica Boa Visão", "Ótica", "óculos", "lentes", "saúde ocular", "exame de vista"] },
    { "id": 10, "name": "Matrix Madeiras", "category": "🌳 Madeireira", "link": "N/A", "keywords": ["Matrix Madeiras", "Madeireira", "madeira", "construção", "reforma", "marcenaria"] },
    { "id": 11, "name": "Auto Peças Vitória", "category": "🚗 Loja de Autopeças", "link": "N/A", "keywords": ["Auto Peças Vitória", "Loja de Autopeças", "peças automotivas", "reposição", "acessórios automotivos", "carro"] },
    { "id": 12, "name": "Bendita Máquina Uniformes e Bordados", "category": "🧵 Serviço de Bordados / Uniformes", "link": "N/A", "keywords": ["Bendita Máquina", "Serviço de Bordados / Uniformes", "uniformes profissionais", "bordados", "personalização", "confecção"] },
    { "id": 13, "name": "Auto Peças Cinco Rodas", "category": "🚗 Loja de Autopeças", "link": "N/A", "keywords": ["Auto Peças Cinco Rodas", "Loja de Autopeças", "peças automotivas", "rodas", "reposição", "acessórios para carro"] },
    { "id": 14, "name": "Ponto Braune Musical - Paciência", "category": "🎼 Loja de Instrumentos Musicais", "link": "N/A", "keywords": ["Ponto Braune Musical", "Loja de Instrumentos Musicais", "instrumentos", "música", "loja de música", "artigos musicais"] },
    { "id": 15, "name": "Nana Import - Comércio de Artigos Infantis", "category": "👶 Loja de Moda Infantil", "link": "N/A", "keywords": ["Nana Import", "Loja de Moda Infantil", "roupa infantil", "artigos para bebê", "moda para crianças", "importados"] },
    { "id": 16, "name": "GD CELL", "category": "📱 Loja de Celulares", "link": "N/A", "keywords": ["GD CELL", "Loja de Celulares", "celulares", "smartphone", "tecnologia", "eletrônicos"] },
    { "id": 17, "name": "VN Imports - Celulares e Acessórios em Geral", "category": "📱 Loja de Celulares / Acessórios", "link": "N/A", "keywords": ["VN Imports", "Loja de Celulares / Acessórios", "celulares", "acessórios para celular", "imports", "tecnologia"] },
    { "id": 18, "name": "Claudinho Biju", "category": "💍 Joalheria Personalizada", "link": "N/A", "keywords": ["Claudinho Biju", "Joalheria Personalizada", "joias", "bijuterias", "personalizados", "presentes"] },
    { "id": 19, "name": "CABO LEO ACESSÓRIOS E TABACARIA", "category": "📱 Loja de Celulares / Acessórios e Tabacaria", "link": "N/A", "keywords": ["CABO LEO", "Loja de Celulares / Acessórios e Tabacaria", "acessórios para celular", "tabacaria", "eletrônicos", "conveniência"] },
    { "id": 20, "name": "O Sol de Kalahari", "category": "🥳 Loja de Artigos para Festas", "link": "N/A", "keywords": ["O Sol de Kalahari", "Loja de Artigos para Festas", "artigos de festa", "decoração", "eventos", "aniversário"] },
    { "id": 21, "name": "FB Moto Oficina Mecânica", "category": "🏍️ Oficina Mecânica de Motos", "link": "N/A", "keywords": ["FB Moto Oficina Mecânica", "Oficina Mecânica de Motos", "mecânica de motos", "manutenção de motos", "serviços para motos", "moto"] },
    { "id": 22, "name": "Mobili Art Móveis", "category": "🛋️ Loja de Móveis", "link": "N/A", "keywords": ["Mobili Art Móveis", "Loja de Móveis", "móveis", "decoração", "casa", "design de interiores"] },
    { "id": 23, "name": "Port Cell Atacadista Comércio de Celulares", "category": "📱 Loja de Celulares (Atacado)", "link": "N/A", "keywords": ["Port Cell Atacadista", "Loja de Celulares (Atacado)", "celulares no atacado", "distribuidor de celular", "revenda", "preços de atacado"] },
    { "id": 24, "name": "Smartec", "category": "📱 Loja de Celulares", "link": "N/A", "keywords": ["Smartec", "Loja de Celulares", "celulares", "smartphone", "tecnologia", "eletrônicos"] },
    { "id": 25, "name": "Ótica Algarve", "category": "👓 Ótica", "link": "N/A", "keywords": ["Ótica Algarve", "Ótica", "óculos", "lentes", "saúde ocular", "exame de vista"] },
    { "id": 26, "name": "Baby Kids Méier", "category": "👶 Loja de Moda Infantil", "link": "N/A", "keywords": ["Baby Kids Méier", "Loja de Moda Infantil", "roupa infantil", "moda bebê", "artigos infantis", "criança"] },
    { "id": 27, "name": "Babalu Modas", "category": "❌ Permanentemente Fechado", "link": "N/A", "keywords": ["Babalu Modas", "Permanentemente Fechado", "loja de roupas", "moda", "vestuário", "fechado"] },
    { "id": 28, "name": "Elza Cosméticos", "category": "💅 Loja de Cosméticos", "link": "N/A", "keywords": ["Elza Cosméticos", "Loja de Cosméticos", "maquiagem", "perfumes", "cuidados pessoais", "beleza"] },
    { "id": 29, "name": "Agita Som", "category": "🔊 Loja de Acessórios Automotivos", "link": "N/A", "keywords": ["Agita Som", "Loja de Acessórios Automotivos", "som automotivo", "acessórios para carro", "equipamentos automotivos", "personalização"] },
    { "id": 30, "name": "Cleber Baterias", "category": "🔋 Loja de Baterias de Carro", "link": "N/A", "keywords": ["Cleber Baterias", "Loja de Baterias de Carro", "baterias automotivas", "troca de bateria", "bateria veicular", "auto peças"] },
    { "id": 31, "name": "PALHAÇADA FESTAS", "category": "🎭 Loja de Fantasias / Artigos para Festas", "link": "N/A", "keywords": ["PALHAÇADA FESTAS", "Loja de Fantasias / Artigos para Festas", "fantasias", "artigos de festa", "decoração de eventos", "aluguel de fantasias"] },
    { "id": 32, "name": "Clínica Odontológica Oral Labor", "category": "🏥 Clínica Odontológica", "link": "N/A", "keywords": ["Clínica Odontológica Oral Labor", "Clínica Odontológica", "dentista", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 33, "name": "Clínica Dr. Ricardo Siqueira", "category": "🏥 Clínica Odontológica", "link": "N/A", "keywords": ["Clínica Dr. Ricardo Siqueira", "Clínica Odontológica", "dentista", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 34, "name": "Cresci e Perdi Santa Cruz", "category": "❌ Permanentemente Fechado", "link": "N/A", "keywords": ["Cresci e Perdi Santa Cruz", "Permanentemente Fechado", "brechó", "loja infantil", "roupa usada", "fechado"] },
    { "id": 35, "name": "Imperio do Açai", "category": "🍓 Açaíteria", "link": "N/A", "keywords": ["Imperio do Açai", "Açaíteria", "açaí", "fast food saudável", "sobremesa", "lanchonete"] },
    { "id": 36, "name": "OAugusto Smartwatch Campo Grande", "category": "⌚ Loja de Eletrônicos / Smartwatches", "link": "N/A", "keywords": ["OAugusto Smartwatch", "Loja de Eletrônicos / Smartwatches", "smartwatch", "relógios inteligentes", "eletrônicos", "tecnologia"] },
    { "id": 37, "name": "Santa Cruz Ferragens", "category": "🛠️ Loja de Materiais de Construção / Ferragens", "link": "N/A", "keywords": ["Santa Cruz Ferragens", "Loja de Materiais de Construção / Ferragens", "ferragens", "material de construção", "ferramentas", "reforma"] },
    { "id": 38, "name": "Leo Eletro - Conserto e Venda", "category": "📱 Oficina de Reparos de Celulares / Venda de Eletrônicos", "link": "N/A", "keywords": ["Leo Eletro", "Oficina de Reparos de Celulares / Venda de Eletrônicos", "conserto de celular", "assistência técnica", "eletrônicos", "venda"] },
    { "id": 39, "name": "Marreco Atacado & Varejo", "category": "📱 Loja de Celulares (Atacado e Varejo)", "link": "N/A", "keywords": ["Marreco Atacado & Varejo", "Loja de Celulares (Atacado e Varejo)", "celulares atacado", "celulares varejo", "distribuidor", "revenda"] },
    { "id": 40, "name": "61 Celular", "category": "📱 Loja de Celulares", "link": "N/A", "keywords": ["61 Celular", "Loja de Celulares", "celulares", "smartphone", "tecnologia", "eletrônicos"] },
    { "id": 41, "name": "Perfil Estúdio de Beleza", "category": "💇‍♀️ Salão de Beleza / Estúdio", "link": "N/A", "keywords": ["Perfil Estúdio de Beleza", "Salão de Beleza / Estúdio", "salão de beleza", "estética", "cuidados pessoais", "beleza"] },
    { "id": 42, "name": "XIBOCA CELL", "category": "📱 Loja de Celulares", "link": "N/A", "keywords": ["XIBOCA CELL", "Loja de Celulares", "celulares", "smartphone", "tecnologia", "eletrônicos"] },
    { "id": 43, "name": "VBB Bazar", "category": "👜 Loja de Malas e Bolsas / Bazar", "link": "N/A", "keywords": ["VBB Bazar", "Loja de Malas e Bolsas / Bazar", "malas", "bolsas", "bazar", "artigos diversos"] },
    { "id": 44, "name": "Conserto CellExpress", "category": "📱 Oficina de Reparos de Celulares", "link": "N/A", "keywords": ["Conserto CellExpress", "Oficina de Reparos de Celulares", "conserto de celular", "assistência técnica", "reparo de smartphone", "serviços de eletrônicos"] },
    { "id": 45, "name": "Soma Plástico", "category": "🧵 Loja de Tecidos / Plásticos", "link": "N/A", "keywords": ["Soma Plástico", "Loja de Tecidos / Plásticos", "tecidos", "plásticos", "aviamentos", "artesanato"] },
    { "id": 46, "name": "CM Rei dos iPhones", "category": "📱 Loja de Celulares (Especializada em iPhones)", "link": "N/A", "keywords": ["CM Rei dos iPhones", "Loja de Celulares", "iPhones", "celulares Apple", "smartphones", "tecnologia"] },
    { "id": 47, "name": "Ótica Nativa", "category": "👓 Ótica", "link": "N/A", "keywords": ["Ótica Nativa", "Ótica", "óculos", "lentes", "saúde ocular", "exame de vista"] },
    { "id": 48, "name": "Loja de Cosméticos em Campo Grande RJ Studio Mulher Cosméticos", "category": "💅 Loja de Cosméticos", "link": "N/A", "keywords": ["Studio Mulher Cosméticos", "Loja de Cosméticos", "maquiagem", "perfumes", "cuidados pessoais", "beleza"] },
    { "id": 49, "name": "Bazar Tem Tudo do Bairro", "category": "🛍️ Bazar / Variedades", "link": "N/A", "keywords": ["Bazar Tem Tudo do Bairro", "Bazar / Variedades", "bazar", "utilidades", "presentes", "artigos gerais"] },
    { "id": 50, "name": "OdontoRiso Dentistas", "category": "🦷 Dentista", "link": "N/A", "keywords": ["OdontoRiso Dentistas", "Dentista", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 51, "name": "Âncora Corretora Campo Grande - RJ", "category": "🛡️ Corretora de Seguros", "link": "N/A", "keywords": ["Âncora Corretora", "Corretora de Seguros", "seguros", "corretagem", "proteção", "finanças"] },
    { "id": 52, "name": "Ótica Sião", "category": "👓 Ótica", "link": "N/A", "keywords": ["Ótica Sião", "Ótica", "óculos", "lentes", "saúde ocular", "exame de vista"] },
    { "id": 53, "name": "Jô Tech Import's", "category": "📱 Loja de Celulares / Importados", "link": "N/A", "keywords": ["Jô Tech Import's", "Loja de Celulares / Importados", "celulares importados", "eletrônicos", "tecnologia", "acessórios"] },
    { "id": 54, "name": "Gráfica e Publicidade Patriota", "category": "🖨️ Gráfica / Publicidade", "link": "N/A", "keywords": ["Gráfica e Publicidade Patriota", "Gráfica / Publicidade", "impressão", "serviços gráficos", "publicidade", "marketing"] },
    { "id": 55, "name": "Show dos Quadros", "category": "🖼️ Loja de Molduras / Quadros", "link": "N/A", "keywords": ["Show dos Quadros", "Loja de Molduras / Quadros", "quadros", "molduras", "decoração", "arte"] },
    { "id": 56, "name": "Bia Cell", "category": "📱 Oficina de Reparos de Celulares", "link": "N/A", "keywords": ["Bia Cell", "Oficina de Reparos de Celulares", "conserto de celular", "assistência técnica", "reparo de smartphone", "serviços de eletrônicos"] },
    { "id": 57, "name": "Mega Cell", "category": "📱 Oficina de Reparos de Celulares", "link": "N/A", "keywords": ["Mega Cell", "Oficina de Reparos de Celulares", "conserto de celular", "assistência técnica", "reparo de smartphone", "serviços de eletrônicos"] },
    { "id": 58, "name": "Rolo Bom Tintas - Loja de Tintas", "category": "🎨 Loja de Tintas", "link": "N/A", "keywords": ["Rolo Bom Tintas", "Loja de Tintas", "tintas", "pintura", "material de pintura", "decoração"] },
    { "id": 59, "name": "Dentista Dr Manuel Guedes", "category": "🦷 Dentista", "link": "N/A", "keywords": ["Dr Manuel Guedes", "Dentista", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 60, "name": "Dr. Regis Paiva - Dentista 45", "category": "🦷 Dentista", "link": "N/A", "keywords": ["Dr. Regis Paiva", "Dentista", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 61, "name": "Robinho Rações", "category": "🐾 Loja de Rações", "link": "N/A", "keywords": ["Robinho Rações", "Loja de Rações", "rações", "pet shop", "alimentos para animais", "artigos pet"] },
    { "id": 62, "name": "Instituto MD - Santa Cruz", "category": "🎓 Centro de Treinamento", "link": "N/A", "keywords": ["Instituto MD Santa Cruz", "Centro de Treinamento", "cursos", "treinamentos", "capacitação profissional", "educação"] },
    { "id": 63, "name": "Instituto MD - Nova Iguaçu", "category": "🎓 Centro de Treinamento", "link": "N/A", "keywords": ["Instituto MD Nova Iguaçu", "Centro de Treinamento", "cursos", "treinamentos", "capacitação profissional", "educação"] },
    { "id": 64, "name": "Neemias Bike", "category": "🚲 Loja de Bicicletas", "link": "N/A", "keywords": ["Neemias Bike", "Loja de Bicicletas", "bicicletas", "ciclismo", "manutenção de bicicletas", "acessórios para bicicleta"] },
    { "id": 65, "name": "Neemias Bike", "category": "🚲 Loja de Bicicletas", "link": "N/A", "keywords": ["Neemias Bike", "Loja de Bicicletas", "bicicletas", "ciclismo", "manutenção de bicicletas", "acessórios para bicicleta"] },
    { "id": 66, "name": "Rei das Motos Elétricas", "category": "🛵 Loja de Bicicletas Elétricas / Scooters", "link": "N/A", "keywords": ["Rei das Motos Elétricas", "Loja de Bicicletas Elétricas / Scooters", "motos elétricas", "scooters elétricas", "mobilidade elétrica", "veículos elétricos"] },
    { "id": 67, "name": "Rei das Motos Elétricas - Santíssimo", "category": "🛵 Loja de Bicicletas Elétricas / Scooters", "link": "N/A", "keywords": ["Rei das Motos Elétricas Santíssimo", "Loja de Bicicletas Elétricas / Scooters", "motos elétricas", "scooters elétricas", "mobilidade elétrica", "veículos elétricos"] },
    { "id": 68, "name": "Rações Menezes", "category": "🐾 Loja de Rações", "link": "N/A", "keywords": ["Rações Menezes", "Loja de Rações", "rações", "pet shop", "alimentos para animais", "artigos pet"] },
    { "id": 69, "name": "HVM Mecânica 4x4", "category": "🔧 Oficina Mecânica (Especializada em 4x4)", "link": "N/A", "keywords": ["HVM Mecânica 4x4", "Oficina Mecânica 4x4", "mecânica 4x4", "off-road", "manutenção veicular", "serviços automotivos"] },
    { "id": 70, "name": "Advance - Odontologia Integrada", "category": "🦷 Dentista / Odontologia Integrada", "link": "N/A", "keywords": ["Advance Odontologia Integrada", "Dentista / Odontologia Integrada", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 71, "name": "Ótica Dr. Óculos Elian", "category": "👓 Ótica", "link": "N/A", "keywords": ["Ótica Dr. Óculos Elian", "Ótica", "óculos", "lentes", "saúde ocular", "exame de vista"] },
    { "id": 72, "name": "CS Locações", "category": "🛠️ Serviço de Locação de Ferramentas", "link": "N/A", "keywords": ["CS Locações", "Serviço de Locação de Ferramentas", "aluguel de ferramentas", "locação de equipamentos", "construção", "reforma"] },
    { "id": 73, "name": "Cirurgião Dentista Dr André Garcia Sepini", "category": "🦷 Cirurgião Dentista", "link": "N/A", "keywords": ["Dr André Garcia Sepini", "Cirurgião Dentista", "dentista", "cirurgia bucal", "implantes", "odontologia"] },
    { "id": 74, "name": "Costura Certa", "category": "🧵 Loja de Máquinas de Costura / Atelier de Costura", "link": "N/A", "keywords": ["Costura Certa", "Loja de Máquinas de Costura / Atelier de Costura", "costura", "máquinas de costura", "consertos de roupas", "customização"] },
    { "id": 75, "name": "WEST IMPORT CELL", "category": "📱 Loja de Acessórios para Dispositivos Móveis", "link": "N/A", "keywords": ["WEST IMPORT CELL", "Loja de Acessórios para Dispositivos Móveis", "acessórios para celular", "capinhas", "carregadores", "fones de ouvido"] },
    { "id": 76, "name": "Shineray Rio Campo Grande - Motocicletas Elétricas - Scooters - Aluguéis de motocicletas - Moto cc.", "category": "🏍️ Loja de Motocicletas (Elétricas, Scooters, Aluguéis)", "link": "N/A", "keywords": ["Shineray Rio Campo Grande", "Loja de Motocicletas", "motos elétricas", "scooters", "aluguel de motos", "concessionária"] },
    { "id": 77, "name": "Odonto Carioca Campo Grande", "category": "🦷 Dentista", "link": "N/A", "keywords": ["Odonto Carioca Campo Grande", "Dentista", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 78, "name": "Odonto Carioca Bangu", "category": "🦷 Dentista", "link": "N/A", "keywords": ["Odonto Carioca Bangu", "Dentista", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 79, "name": "Bira Cell", "category": "📱 Loja de Acessórios para Dispositivos Móveis", "link": "N/A", "keywords": ["Bira Cell", "Loja de Acessórios para Dispositivos Móveis", "acessórios para celular", "capinhas", "carregadores", "fones de ouvido"] },
    { "id": 80, "name": "TONS E CORES TINTAS", "category": "🎨 Loja de Tintas", "link": "N/A", "keywords": ["TONS E CORES TINTAS", "Loja de Tintas", "tintas", "pintura", "material de pintura", "decoração"] },
    { "id": 81, "name": "Facilidente", "category": "🦷 Dentista", "link": "N/A", "keywords": ["Facilidente", "Dentista", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 82, "name": "Dentista Dr. Eduardo Reis", "category": "🦷 Dentista", "link": "N/A", "keywords": ["Dr. Eduardo Reis", "Dentista", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 83, "name": "Dental e Tal Suprimentos Odontológicos", "category": "🦷 Loja de Produtos Odontológicos", "link": "N/A", "keywords": ["Dental e Tal", "Loja de Produtos Odontológicos", "suprimentos dentários", "material odontológico", "equipamentos", "odontologia"] },
    { "id": 84, "name": "Rede Home Express", "category": "🧱 Loja de Materiais de Construção", "link": "N/A", "keywords": ["Rede Home Express", "Loja de Materiais de Construção", "material de obra", "reforma", "construção", "casa"] },
    { "id": 85, "name": "Kanguru's Boliche", "category": "🎳 Restaurante / Boliche", "link": "N/A", "keywords": ["Kanguru's Boliche", "Restaurante / Boliche", "boliche", "diversão", "restaurante", "entretenimento"] },
    { "id": 86, "name": "Desentupidora Hidro Porto Diadema", "category": "🚰 Desentupidora", "link": "N/A", "keywords": ["Hidro Porto Diadema", "Desentupidora", "desentupimento", "serviços hidráulicos", "encanamento", "limpeza de esgoto"] },
    { "id": 87, "name": "Marco Alpha Climax Ar condicionado", "category": "❄️ Prestador de Serviços de Climatização", "link": "N/A", "keywords": ["Marco Alpha Climax", "Serviços de Climatização", "ar condicionado", "instalação de ar", "manutenção de ar", "climatização"] },
    { "id": 88, "name": "WF Gráfica Rápida e Impressão Digital", "category": "🖨️ Gráfica Rápida / Impressão Digital", "link": "N/A", "keywords": ["WF Gráfica Rápida", "Gráfica Rápida / Impressão Digital", "serviços gráficos", "impressão digital", "gráfica", "design gráfico"] },
    { "id": 89, "name": "Knupp Odontologia - Dra. Manon Knupp", "category": "🦷 Dentista", "link": "N/A", "keywords": ["Dra. Manon Knupp", "Dentista", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 90, "name": "Shineray Recreio", "category": "🏍️ Concessionária de Motocicletas", "link": "N/A", "keywords": ["Shineray Recreio", "Concessionária de Motocicletas", "motos", "shineray", "concessionária", "moto nova"] },
    { "id": 91, "name": "Shineray Motors Jacarepaguá", "category": "🏍️ Concessionária de Motocicletas", "link": "N/A", "keywords": ["Shineray Motors Jacarepaguá", "Concessionária de Motocicletas", "motos", "shineray", "concessionária", "moto nova"] },
    { "id": 92, "name": "Recreio Máquinas", "category": "🍴 Loja de Utensílios de Cozinha", "link": "N/A", "keywords": ["Recreio Máquinas", "Loja de Utensílios de Cozinha", "utensílios de cozinha", "equipamentos de cozinha", "panelas", "eletrodomésticos"] },
    { "id": 93, "name": "Philos Assessoria Contábil", "category": "📊 Assessoria Contábil", "link": "N/A", "keywords": ["Philos Assessoria Contábil", "Assessoria Contábil", "contabilidade", "serviços contábeis", "assessoria", "consultoria"] },
    { "id": 94, "name": "ITS Odontologia Digital | Paciência", "category": "🦷 Dentista / Odontologia Digital", "link": "N/A", "keywords": ["ITS Odontologia Digital", "Dentista / Odontologia Digital", "odontologia digital", "clínica odontológica", "tratamento dentário", "saúde bucal"] },
    { "id": 95, "name": "Archipéva Odontologia", "category": "🦷 Dentista", "link": "N/A", "keywords": ["Archipéva Odontologia", "Dentista", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 96, "name": "CF Materiais de Construção", "category": "🧱 Loja de Materiais de Construção", "link": "N/A", "keywords": ["CF Materiais de Construção", "Loja de Materiais de Construção", "material de obra", "reforma", "construção", "casa"] },
    { "id": 97, "name": "Drenamais Estética e Fisioterapia", "category": "✨ Esteticista / Fisioterapia", "link": "N/A", "keywords": ["Drenamais Estética e Fisioterapia", "Esteticista / Fisioterapia", "estética", "fisioterapia", "bem-estar", "saúde e beleza"] },
    { "id": 98, "name": "Toca do Leão", "category": "💊 Loja de Vitaminas e Suplementos", "link": "N/A", "keywords": ["Toca do Leão", "Loja de Vitaminas e Suplementos", "vitaminas", "suplementos", "saúde", "bem-estar"] },
    { "id": 99, "name": "Cabana do Bolo", "category": "🎂 Loja de Bolos", "link": "N/A", "keywords": ["Cabana do Bolo", "Loja de Bolos", "bolos", "confeitaria", "doces", "festa"] },
    { "id": 100, "name": "Ionete Laços - Boutique de Meninas", "category": "🎀 Artesanato", "link": "N/A", "keywords": ["Ionete Laços", "Artesanato", "laços", "artesanato", "acessórios infantis", "boutique"] },
    { "id": 101, "name": "Depósito Mini BR", "category": "🍾 Loja de Bebidas", "link": "N/A", "keywords": ["Depósito Mini BR", "Loja de Bebidas", "bebidas", "depósito de bebidas", "cerveja", "refrigerante"] },
    { "id": 102, "name": "Dadal Auto Mecânica", "category": "🔧 Oficina Mecânica", "link": "N/A", "keywords": ["Dadal Auto Mecânica", "Oficina Mecânica", "mecânica automotiva", "manutenção veicular", "serviços automotivos", "carro"] },
    { "id": 103, "name": "Rosana Ramos Confeitaria", "category": "🍰 Confeitaria", "link": "N/A", "keywords": ["Rosana Ramos Confeitaria", "Confeitaria", "bolos", "doces", "salgados", "confeitaria artesanal"] },
    { "id": 104, "name": "BARBEARIA DO ZEZINHO JZ", "category": "💈 Barbearia", "link": "N/A", "keywords": ["BARBEARIA DO ZEZINHO JZ", "Barbearia", "corte de cabelo masculino", "barba", "cabelo e barba", "salão masculino"] },
    { "id": 105, "name": "Dany's Festas", "category": "🎉 Serviços para Casamento", "link": "N/A", "keywords": ["Dany's Festas", "Serviços para Casamento", "casamento", "eventos", "organização de festas", "buffet"] },
    { "id": 106, "name": "Nova Odonto Plus", "category": "🦷 Dentista", "link": "N/A", "keywords": ["Nova Odonto Plus", "Dentista", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 107, "name": "FR Dental Clinic", "category": "🦷 Dentista", "link": "N/A", "keywords": ["FR Dental Clinic", "Dentista", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 108, "name": "Material de Construcao Central de Cosmos", "category": "🧱 Loja de Materiais de Construção", "link": "N/A", "keywords": ["Material de Construcao Central de Cosmos", "Loja de Materiais de Construção", "material de obra", "reforma", "construção", "casa"] },
    { "id": 109, "name": "JM Confeitaria", "category": "🍰 Confeitaria", "link": "N/A", "keywords": ["JM Confeitaria", "Confeitaria", "bolos", "doces", "salgados", "confeitaria artesanal"] },
    { "id": 110, "name": "Recanto dos Pés", "category": "🦶🏻 Podólogo", "link": "N/A", "keywords": ["Recanto dos Pés", "Podólogo", "podologia", "saúde dos pés", "cuidados com os pés", "tratamento podológico"] },
    { "id": 111, "name": "Facilita Multas e Recursos", "category": "👩‍⚖️ Assistência Jurídica", "link": "N/A", "keywords": ["Facilita Multas e Recursos", "Assistência Jurídica", "recurso de multa", "direito de trânsito", "advocacia", "serviços jurídicos"] },
    { "id": 112, "name": "Wan Dall Jóias", "category": "💎 Joalheria", "link": "N/A", "keywords": ["Wan Dall Jóias", "Joalheria", "joias", "ouro", "prata", "acessórios de luxo"] },
    { "id": 113, "name": "Clínica Vitallis", "category": "🏥 Clínica Odontológica", "link": "N/A", "keywords": ["Clínica Vitallis", "Clínica Odontológica", "dentista", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 114, "name": "Dogdal Rações na Brisa - Rações para Animais - Farmácia Veterinária - Materiais de Pesca", "category": "🐾 Loja de Rações / Pet Shop", "link": "N/A", "keywords": ["Dogdal Rações na Brisa", "Loja de Rações / Pet Shop", "rações", "pet shop", "farmácia veterinária", "artigos pet"] },
    { "id": 115, "name": "Dogdal Rações em Inhoaíba - Rações para Animais - Farmácia Veterinária - Materiais de Pesca", "category": "🐾 Loja de Rações / Pet Shop", "link": "N/A", "keywords": ["Dogdal Rações em Inhoaíba", "Loja de Rações / Pet Shop", "rações", "pet shop", "farmácia veterinária", "artigos pet"] },
    { "id": 116, "name": "Albuquerque e Lima - Advocacia Previdenciária - Estrada do Campinho", "category": "🧑‍⚖️ Advogado Previdenciário", "link": "N/A", "keywords": ["Albuquerque e Lima", "Advocacia Previdenciária", "advogado", "direito previdenciário", "aposentadoria", "serviços jurídicos"] },
    { "id": 117, "name": "Leonardo Alves Dentista - L.A Odontologia", "category": "🏥 Clínica Odontológica", "link": "N/A", "keywords": ["Leonardo Alves Dentista", "Clínica Odontológica", "dentista", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 118, "name": "L.A Leonardo Alves Odontologia Avançada", "category": "🏥 Clínica Odontológica", "link": "N/A", "keywords": ["L.A Leonardo Alves Odontologia Avançada", "Clínica Odontológica", "dentista", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 119, "name": "pet shop CAT & DOG-RECREIO", "category": "🐶 Pet Shop", "link": "N/A", "keywords": ["pet shop CAT & DOG-RECREIO", "Pet Shop", "banho e tosa", "acessórios para pets", "clínica veterinária", "cuidados pet"] },
    { "id": 120, "name": "Sampaio Imóveis", "category": "🏠 Imobiliária", "link": "N/A", "keywords": ["Sampaio Imóveis", "Imobiliária", "imóveis", "aluguel", "venda", "corretagem"] },
    { "id": 121, "name": "SV Motos Tijuca", "category": "🏍️ Concessionária de Motocicletas", "link": "N/A", "keywords": ["SV Motos Tijuca", "Concessionária de Motocicletas", "motos", "concessionária", "moto nova", "moto usada"] },
    { "id": 122, "name": "CACHO ESSENCIAL INSTITUTO DE BELEZA E TERAPIA CAPILAR", "category": "💇‍♀️ Salão de Beleza / Terapia Capilar", "link": "N/A", "keywords": ["CACHO ESSENCIAL", "Salão de Beleza / Terapia Capilar", "salão de beleza", "terapia capilar", "cabelos", "beleza"] },
    { "id": 123, "name": "Kengão Material de Construção", "category": "🧱 Loja de Materiais de Construção", "link": "N/A", "keywords": ["Kengão Material de Construção", "Loja de Materiais de Construção", "material de obra", "reforma", "construção", "casa"] },
    { "id": 124, "name": "Eskimó Sorvetes Sepetiba", "category": "🍦 Sorveteria", "link": "N/A", "keywords": ["Eskimó Sorvetes Sepetiba", "Sorveteria", "sorvetes", "gelateria", "sobremesas", "doces"] },
    { "id": 125, "name": "GRICS Rodrigues Advocacia", "category": "🧑‍⚖️ Advogado Previdenciário", "link": "N/A", "keywords": ["GRICS Rodrigues Advocacia", "Advogado Previdenciário", "advogado", "direito previdenciário", "aposentadoria", "serviços jurídicos"] },
    { "id": 126, "name": "Aviário Central do Monteiro", "category": "🥩 Açougue / Aviário", "link": "N/A", "keywords": ["Aviário Central do Monteiro", "Açougue / Aviário", "carnes", "frangos", "açougue", "produtos frescos"] },
    { "id": 127, "name": "Nayara Ribeiro - Advogado(a) de Usucapião, Inventário, Divórcio e Regularização Imobiliária - Campo Grande/RJ - Zona Oeste", "category": "👩‍⚖️ Advogado", "link": "N/A", "keywords": ["Nayara Ribeiro", "Advogado", "advocacia", "serviços jurídicos", "direito imobiliário", "família"] },
    { "id": 128, "name": "Dra.Keila Cabral | Clinica odontologica | Cirurgião Dentista | Paciência", "category": "🏥 Clínica Odontológica / Cirurgião Dentista", "link": "N/A", "keywords": ["Dra.Keila Cabral", "Clínica Odontológica / Cirurgião Dentista", "dentista", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 129, "name": "Luma Gás Campo Grande RJ", "category": "⛽ Centro de Instalação de GNV para Automóveis", "link": "N/A", "keywords": ["Luma Gás Campo Grande RJ", "Centro de Instalação de GNV", "gnv", "gás veicular", "instalação", "conversão"] },
    { "id": 130, "name": "Massoterapia E Estética - Dora Freitas", "category": "💆‍♀️ Massoterapeuta / Estética", "link": "N/A", "keywords": ["Dora Freitas", "Massoterapeuta / Estética", "massagem", "estética corporal", "bem-estar", "relaxamento"] },
    { "id": 131, "name": "Ana Nunes Estética e Beleza", "category": "✨ Centro de Saúde e Beleza", "link": "N/A", "keywords": ["Ana Nunes Estética e Beleza", "Centro de Saúde e Beleza", "estética", "beleza", "cuidados pessoais", "bem-estar"] },
    { "id": 132, "name": "SM Soluções e Montagens", "category": "🛠️ Reformas / Montagens", "link": "N/A", "keywords": ["SM Soluções e Montagens", "Reformas / Montagens", "reformas", "montagens", "serviços de construção", "manutenção"] },
    { "id": 133, "name": "Douglas Almeida - Óculos a Preço Justo", "category": "👓 Ótica", "link": "N/A", "keywords": ["Douglas Almeida", "Ótica", "óculos", "lentes", "saúde ocular", "exame de vista"] },
    { "id": 134, "name": "Rufino Advocacia", "category": "⚖️ Escritório de Advocacia", "link": "N/A", "keywords": ["Rufino Advocacia", "Escritório de Advocacia", "advocacia", "serviços jurídicos", "direito", "consultoria jurídica"] },
    { "id": 135, "name": "Rufino Engenharia", "category": "👷 Engenharia", "link": "N/A", "keywords": ["Rufino Engenharia", "Engenharia", "serviços de engenharia", "projetos", "construção", "consultoria"] },
    { "id": 136, "name": "SINALIZA LOCADORA DE MOTOS", "category": "🏍️ Concessionária de Motocicletas / Locadora", "link": "N/A", "keywords": ["SINALIZA LOCADORA DE MOTOS", "Concessionária de Motocicletas / Locadora", "aluguel de motos", "motos", "locação", "concessionária"] },
    { "id": 137, "name": "SV AUTOMÓVEIS", "category": "🚘 Concessionária de Automóveis", "link": "N/A", "keywords": ["SV AUTOMÓVEIS", "Concessionária de Automóveis", "carros", "veículos", "concessionária", "venda de carros"] },
    { "id": 138, "name": "SÓ Multas Paciência", "category": "📄 Serviços Administrativos", "link": "N/A", "keywords": ["SÓ Multas Paciência", "Serviços Administrativos", "recurso de multas", "despachante", "documentação", "serviços burocráticos"] },
    { "id": 139, "name": "df Despachante", "category": "✍️ Despachante", "link": "N/A", "keywords": ["df Despachante", "Despachante", "documentação veicular", "licenciamento", "transferência", "serviços de despachante"] },
    { "id": 140, "name": "Rota 22 - Estúdio de Tatuagem e Piercing", "category": "🎨 Estúdio de Tatuagem e Colocação de Piercing", "link": "N/A", "keywords": ["Rota 22", "Estúdio de Tatuagem e Piercing", "tatuagem", "piercing", "body art", "arte corporal"] },
    { "id": 141, "name": "Randow Smart", "category": "📱 Loja de Eletrônicos", "link": "N/A", "keywords": ["Randow Smart", "Loja de Eletrônicos", "eletrônicos", "tecnologia", "gadgets", "dispositivos"] },
    { "id": 142, "name": "ÓTICA VER BEM", "category": "👓 Ótica", "link": "N/A", "keywords": ["ÓTICA VER BEM", "Ótica", "óculos", "lentes", "saúde ocular", "exame de vista"] },
    { "id": 143, "name": "Refeições da Renata", "category": "🍽️ Restaurante", "link": "N/A", "keywords": ["Refeições da Renata", "Restaurante", "refeições", "comida caseira", "almoço", "jantar"] },
    { "id": 144, "name": "Robcell Point dos Acessórios", "category": "📱 Loja de Celulares / Acessórios", "link": "N/A", "keywords": ["Robcell Point dos Acessórios", "Loja de Celulares / Acessórios", "acessórios para celular", "capinhas", "carregadores", "fones de ouvido"] },
    { "id": 145, "name": "Robcell Consertos em Geral", "category": "📱 Oficina de Conserto de Eletrônicos", "link": "N/A", "keywords": ["Robcell Consertos em Geral", "Oficina de Conserto de Eletrônicos", "conserto de eletrônicos", "assistência técnica", "reparo de dispositivos", "manutenção"] },
    { "id": 146, "name": "Casa Colibri Espaço Infantil", "category": "👧 Pré-escola / Espaço Infantil", "link": "N/A", "keywords": ["Casa Colibri", "Pré-escola / Espaço Infantil", "educação infantil", "creche", "recreação", "desenvolvimento infantil"] },
    { "id": 147, "name": "CMN Auto Center - Oficina Mecânica Campo Grande RJ", "category": "🔧 Oficina Mecânica / Auto Center", "link": "N/A", "keywords": ["CMN Auto Center", "Oficina Mecânica / Auto Center", "mecânica automotiva", "manutenção veicular", "serviços automotivos", "carro"] },
    { "id": 148, "name": "Clínica Odontológica Sorria Penha (unidade Recreio)", "category": "🏥 Clínica Odontológica", "link": "N/A", "keywords": ["Clínica Odontológica Sorria Penha", "Clínica Odontológica", "dentista", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 149, "name": "MUSCLE FIT", "category": "🏋️ Academia", "link": "N/A", "keywords": ["MUSCLE FIT", "Academia", "treino", "fitness", "musculação", "saúde e bem-estar"] },
    { "id": 150, "name": "Casa Maçã", "category": "📱 Loja de Celulares", "link": "N/A", "keywords": ["Casa Maçã", "Loja de Celulares", "celulares", "smartphone", "tecnologia", "eletrônicos"] },
    { "id": 151, "name": "Sorriclinica Dentistas", "category": "🦷 Dentista", "link": "https://g.co/kgs/BYtrPvn", "keywords": ["Sorriclinica Dentistas", "Dentista", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 152, "name": "Clínica Gustavo Martins - Especialista em Face", "category": "👨‍⚕️ Cirurgião Dentista / Especialista em Face", "link": "https://g.co/kgs/KWjsU22", "keywords": ["Clínica Gustavo Martins", "Cirurgião Dentista / Especialista em Face", "cirurgia facial", "dentista", "estética facial", "odontologia"] },
    { "id": 153, "name": "Vai de Boa Tecnologia", "category": "💻 Tecnologia", "link": "N/A", "keywords": ["Vai de Boa Tecnologia", "Tecnologia", "soluções em TI", "consultoria em tecnologia", "desenvolvimento", "inovação"] },
    { "id": 154, "name": "Dentista em Campo Grande RJ - LC Odontologia e Medicina Integrada", "category": "🦷 Dentista / Clínica Odontológica", "link": "N/A", "keywords": ["LC Odontologia e Medicina Integrada", "Dentista / Clínica Odontológica", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 155, "name": "Alca2C", "category": "💻 Tecnologia", "link": "N/A", "keywords": ["Alca2C", "Tecnologia", "soluções em TI", "consultoria em tecnologia", "desenvolvimento", "inovação"] },
    { "id": 156, "name": "Bons Vizinhos Tintas e Material de Construção", "category": "🧱 Loja de Tintas e Materiais de Construção", "link": "N/A", "keywords": ["Bons Vizinhos Tintas e Material de Construção", "Loja de Tintas e Materiais de Construção", "tintas", "material de construção", "reforma", "casa"] },
    { "id": 157, "name": "Monobloco Serviços Automotivos", "category": "🔧 Oficina Mecânica", "link": "N/A", "keywords": ["Monobloco Serviços Automotivos", "Oficina Mecânica", "mecânica automotiva", "manutenção veicular", "serviços automotivos", "carro"] },
    { "id": 158, "name": "Personalle Espaço de Beleza", "category": "💇‍♀️ Salão de Beleza / Estética", "link": "N/A", "keywords": ["Personalle Espaço de Beleza", "Salão de Beleza / Estética", "salão de beleza", "estética", "cuidados pessoais", "beleza"] },
    { "id": 159, "name": "Bar Boa Praça", "category": "🍻 Bar / Restaurante", "link": "N/A", "keywords": ["Bar Boa Praça", "Bar / Restaurante", "bar", "restaurante", "comida", "bebidas"] },
    { "id": 160, "name": "HP Consultoria", "category": "📊 Consultoria Financeira", "link": "N/A", "keywords": ["HP Consultoria", "Consultoria Financeira", "consultoria", "finanças", "negócios", "planejamento"] },
    { "id": 161, "name": "Amor Perfeito - Bebê Reborn", "category": "🧸 Loja de Bonecas", "link": "N/A", "keywords": ["Amor Perfeito", "Loja de Bonecas", "bonecas", "bebê reborn", "brinquedos", "colecionáveis"] },
    { "id": 162, "name": "Centro Odontológico Dra. Leila Márcia", "category": "🏥 Clínica Odontológica", "link": "N/A", "keywords": ["Dra. Leila Márcia", "Clínica Odontológica", "dentista", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 163, "name": "Auto Escola Heringer", "category": "🚗 Auto Escola", "link": "https://g.co/kgs/cpfBJ9v", "keywords": ["Auto Escola Heringer", "Auto Escola", "carteira de motorista", "aulas de direção", "habilitação", "primeira habilitação"] },
    { "id": 164, "name": "Albuquerque e Lima - Advocacia Previdenciária - Campo Grande", "category": "⚖️ Serviços Jurídicos / Advocacia", "link": "https://g.co/kgs/vqm8Gg4", "keywords": ["Albuquerque e Lima", "Serviços Jurídicos / Advocacia", "advocacia", "direito", "serviços jurídicos", "consultoria jurídica"] },
    { "id": 165, "name": "Ponto Braune Musical - Santa Cruz", "category": "🎼 Loja de Instrumentos Musicais", "link": "https://g.co/kgs/rLyP9sP", "keywords": ["Ponto Braune Musical", "Loja de Instrumentos Musicais", "instrumentos", "música", "loja de música", "artigos musicais"] },
    { "id": 166, "name": "RioUp! Imóveis", "category": "🏠 Imobiliária", "link": "https://g.co/kgs/jvY9jXY", "keywords": ["RioUp! Imóveis", "Imobiliária", "imóveis", "aluguel", "venda", "corretagem"] },
    { "id": 167, "name": "Recanto dos Pés Bangu", "category": "🦶🏻 Podólogo", "link": "https://g.co/kgs/GgidNYM", "keywords": ["Recanto dos Pés Bangu", "Podólogo", "podologia", "saúde dos pés", "cuidados com os pés", "tratamento podológico"] },
    { "id": 168, "name": "Nhoque da Vânia", "category": "🍝 Loja de Massas", "link": "https://g.co/kgs/xev2X9E", "keywords": ["Nhoque da Vânia", "Loja de Massas", "massas", "culinária italiana", "comida", "refeições"] },
    { "id": 169, "name": "Jardim Do Éden", "category": "💐 Floricultura", "link": "https://share.google/xwnLhQvmgEEnxBHTO", "keywords": ["Jardim Do Éden", "Floricultura", "flores", "plantas", "arranjos", "jardinagem"] },
    { "id": 170, "name": "Miss Esmalteria e Beleza", "category": "💇‍♀️ Salão de Beleza / Estética / Esmalteria", "link": "https://g.co/kgs/CaM41c7", "keywords": ["Miss Esmalteria e Beleza", "Salão de Beleza / Estética / Esmalteria", "salão de beleza", "esmaltaria", "estética", "manicure"] },
    { "id": 171, "name": "Relojoeiro em Cosmo (Edgar)", "category": "⌚ Relojoeiro", "link": "https://g.co/kgs/o2Mf2EV", "keywords": ["Relojoeiro em Cosmo", "Relojoeiro", "conserto de relógios", "relógios", "joias", "baterias"] },
    { "id": 172, "name": "Auto Escola Premium", "category": "🚗 Auto Escola", "link": "https://g.co/kgs/wMrdrcv", "keywords": ["Auto Escola Premium", "Auto Escola", "carteira de motorista", "aulas de direção", "habilitação", "primeira habilitação"] },
    { "id": 173, "name": "Abratec Serviços Automotivos", "category": "🚘 Oficina Mecânica / Auto Center", "link": "https://g.co/kgs/GXVUvff", "keywords": ["Abratec Serviços Automotivos", "Oficina Mecânica / Auto Center", "mecânica automotiva", "manutenção veicular", "serviços automotivos", "carro"] },
    { "id": 174, "name": "Confiança Assessoria Imobiliária LTDA", "category": "🏠 Imobiliária", "link": "https://g.co/kgs/AQx5mCV", "keywords": ["Confiança Assessoria Imobiliária LTDA", "Imobiliária", "imóveis", "aluguel", "venda", "corretagem"] },
    { "id": 175, "name": "MR AUTOMOTIVOS - AUTO ELÉTRICA", "category": "🚘 Oficina Mecânica / Auto Center", "link": "https://g.co/kgs/Vx2DwnE", "keywords": ["MR AUTOMOTIVOS", "Oficina Mecânica / Auto Center", "mecânica automotiva", "auto elétrica", "manutenção veicular", "serviços automotivos"] },
    { "id": 176, "name": "Veterinária Paciência", "category": "🐾 Veterinário", "link": "https://g.co/kgs/UvT7hJr", "keywords": ["Veterinária Paciência", "Veterinário", "clínica veterinária", "saúde animal", "atendimento pet", "vacinação"] },
    { "id": 177, "name": "Atlantic Soluções", "category": "🏗️ Engenharia / Construção / Reformas / Montagens", "link": "https://g.co/kgs/BtnHfJr", "keywords": ["Atlantic Soluções", "Engenharia / Construção / Reformas / Montagens", "engenharia civil", "construção", "reformas", "projetos"] },
    { "id": 178, "name": "Avant Negócios Imobiliários", "category": "🏠 Imobiliária", "link": "https://g.co/kgs/V3n24ok", "keywords": ["Avant Negócios Imobiliários", "Imobiliária", "imóveis", "aluguel", "venda", "corretagem"] },
    { "id": 179, "name": "Cathal Produtos e Serviços", "category": "🧴 Produtos de Limpeza e Utilidades", "link": "https://g.co/kgs/wr77CBX", "keywords": ["Cathal Produtos e Serviços", "Produtos de Limpeza e Utilidades", "limpeza", "utilidades domésticas", "produtos de limpeza", "casa"] },
    { "id": 180, "name": "Gauchão Madeiras", "category": "🌳 Madeireira", "link": "https://g.co/kgs/XjBGwrZ", "keywords": ["Gauchão Madeiras", "Madeireira", "madeira", "construção", "reforma", "marcenaria"] },
    { "id": 181, "name": "Oral Imagem - Campo Grande RJ", "category": "🏥 Clínica Odontológica / Dentistas", "link": "https://g.co/kgs/Pf3SbRJ", "keywords": ["Oral Imagem", "Clínica Odontológica / Dentistas", "dentista", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 182, "name": "Clinica Cher", "category": "🏥 Clínica Odontológica / Dentistas", "link": "https://g.co/kgs/oSSPq3n", "keywords": ["Clinica Cher", "Clínica Odontológica / Dentistas", "dentista", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 183, "name": "A&L Conceito Automotivo", "category": "🚘 Oficina Mecânica / Auto Center", "link": "https://g.co/kgs/a4Z8m9M", "keywords": ["A&L Conceito Automotivo", "Oficina Mecânica / Auto Center", "mecânica automotiva", "manutenção veicular", "serviços automotivos", "carro"] },
    { "id": 184, "name": "Restaurante Espeto Gaúcho - Rua Aurélio", "category": "🍽️ Restaurante", "link": "https://g.co/kgs/UgLfFfq", "keywords": ["Restaurante Espeto Gaúcho", "Restaurante", "comida", "refeições", "culinária", "gastronomia"] },
    { "id": 185, "name": "Sr. CAFEZIN", "category": "☕ Cafeteria", "link": "https://g.co/kgs/9uGiWjN", "keywords": ["Sr. CAFEZIN", "Cafeteria", "café", "cafeteria", "lanchonete", "bebidas"] },
    { "id": 186, "name": "Elseg Equipamentos", "category": "🛠️ Loja de Equipamentos", "link": "https://g.co/kgs/3V6qFzE", "keywords": ["Elseg Equipamentos", "Loja de Equipamentos", "equipamentos", "ferramentas", "máquinas", "manutenção"] },
    { "id": 187, "name": "Rancho Café na Roça", "category": "☕ Cafeteria", "link": "https://g.co/kgs/NDM3LYh", "keywords": ["Rancho Café na Roça", "Cafeteria", "café", "cafeteria", "lanchonete", "bebidas"] },
    { "id": 188, "name": "Dental Clean - Sepetiba", "category": "🏥 Clínica Odontológica / Dentistas", "link": "https://g.co/kgs/zmNGswY", "keywords": ["Dental Clean", "Clínica Odontológica / Dentistas", "dentista", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 189, "name": "Four Patinhas Veterinária", "category": "🐾 Veterinário", "link": "https://g.co/kgs/pS1CKdt", "keywords": ["Four Patinhas Veterinária", "Veterinário", "clínica veterinária", "saúde animal", "atendimento pet", "vacinação"] },
    { "id": 190, "name": "Réglicred Empréstimo - São Cristóvão", "category": "💰 Agência de Empréstimos no Rio de Janeiro", "link": "https://g.co/kgs/RXTCssv", "keywords": ["Réglicred Empréstimo", "Agência de Empréstimos", "empréstimos", "crédito", "financiamento", "serviços financeiros"] },
    { "id": 191, "name": "Serralheria e Vidraçaria M.A - Campo Grande RJ", "category": "🔨 Serralheria e Vidraçaria", "link": "https://g.co/kgs/WWr8Kyh", "keywords": ["Serralheria e Vidraçaria M.A", "Serralheria e Vidraçaria", "serralheria", "vidraçaria", "portões", "esquadrias"] },
    { "id": 192, "name": "OAugusto Smartwatch Iaraquã", "category": "📱 Loja de Celulares / Acessórios de Celulares", "link": "https://g.co/kgs/SQgj6tk", "keywords": ["OAugusto Smartwatch", "Loja de Celulares / Acessórios de Celulares", "celulares", "acessórios para celular", "smartwatch", "eletrônicos"] },
    { "id": 193, "name": "Curso Mourão", "category": "📚 Cursos", "link": "https://g.co/kgs/3ed5kF8", "keywords": ["Curso Mourão", "Cursos", "educação", "ensino", "capacitação profissional", "aulas"] },
    { "id": 194, "name": "Virtus Celular - Cosmos RJ", "category": "📱 Loja de Celulares / Acessórios de Celulares", "link": "https://g.co/kgs/uDVWLXj", "keywords": ["Virtus Celular", "Loja de Celulares / Acessórios de Celulares", "celulares", "acessórios para celular", "smartphones", "eletrônicos"] },
    { "id": 195, "name": "Jonathan Pneus | Borracharia 24h (R.Prof. Gonçalves)", "category": "🛞 Borracharia", "link": "https://g.co/kgs/6FWUQyP", "keywords": ["Jonathan Pneus", "Borracharia", "pneus", "borracharia 24h", "conserto de pneu", "alinhamento"] },
    { "id": 196, "name": "Grande Rio Pneus", "category": "🛠️ Mecânica para Carros", "link": "https://g.co/kgs/UfYoJNj", "keywords": ["Grande Rio Pneus", "Mecânica para Carros", "mecânica automotiva", "pneus", "manutenção veicular", "serviços automotivos"] },
    { "id": 197, "name": "Iluminare Elétrica", "category": "💡 Loja de Iluminação", "link": "https://g.co/kgs/ZYKix1c", "keywords": ["Iluminare Elétrica", "Loja de Iluminação", "iluminação", "materiais elétricos", "luminárias", "decoração"] },
    { "id": 198, "name": "#244 Moto Peças e Oficina de Moto", "category": "🏍️ Loja de Peças para Motocicletas", "link": "https://g.co/kgs/UYbTiZf", "keywords": ["244 Moto Peças", "Loja de Peças para Motocicletas", "peças de moto", "acessórios para moto", "oficina de moto", "manutenção de motos"] },
    { "id": 199, "name": "MotoChefe - Campo Grande", "category": "🛵 Concessionária de Scooters Elétricas", "link": "https://g.co/kgs/Z2GHkxT", "keywords": ["MotoChefe", "Concessionária de Scooters Elétricas", "scooters elétricas", "motos elétricas", "mobilidade elétrica", "concessionária"] },
    { "id": 200, "name": "Bilha Motos", "category": "🏍️ Loja de Peças para Motocicletas", "link": "https://g.co/kgs/42QbF49", "keywords": ["Bilha Motos", "Loja de Peças para Motocicletas", "peças de moto", "acessórios para moto", "oficina de moto", "manutenção de motos"] },
    { "id": 201, "name": "Ótica Moulin - Santa Cruz", "category": "🕶️ Óticas", "link": "https://g.co/kgs/Eh4tRWU", "keywords": ["Ótica Moulin", "Óticas", "óculos", "lentes", "saúde ocular", "exame de vista"] },
    { "id": 202, "name": "Spidd Motos - Campo Grande RJ", "category": "🔧 Oficina Mecânica de Motos", "link": "https://share.google/AQxx4CBjomkgLlFuF", "keywords": ["Spidd Motos", "Oficina Mecânica de Motos", "mecânica de motos", "manutenção de motos", "serviços para motos", "moto"] },
    { "id": 203, "name": "Ótica Vilage", "category": "👓 Ótica", "link": "https://share.google/Ges515BV7KIxAX07H", "keywords": ["Ótica Vilage", "Ótica", "óculos", "lentes", "saúde ocular", "exame de vista"] },
    { "id": 204, "name": "Mallu Móveis | Móveis para Salão de Beleza", "category": "🛋️ Loja de móveis", "link": "https://share.google/3Axt3DxrLwOfpFb4O", "keywords": ["Mallu Móveis", "Loja de móveis", "móveis para salão de beleza", "móveis", "decoração", "mobiliário"] },
    { "id": 205, "name": "Lu do Piercing", "category": "🎨 Estúdio de tatuagem e colocação de piercing", "link": "https://share.google/EHpfwdaFg2PzNcpRl", "keywords": ["Lu do Piercing", "Estúdio de tatuagem e colocação de piercing", "piercing", "body art", "joias corporais", "perfuração"] },
    { "id": 206, "name": "Jonathan Pneus | Borracharia 24h (Cachamorra)", "category": "🛞 Borracharia", "link": "https://share.google/fKn8Xqy0TTDLEaxrj", "keywords": ["Jonathan Pneus", "Borracharia", "pneus", "borracharia 24h", "conserto de pneu", "alinhamento"] },
    { "id": 207, "name": "DNA Kids Moda Baby e Infantil", "category": "👶 Loja de moda infantil", "link": "https://share.google/8AiqDm0n9KAmewm3n", "keywords": ["DNA Kids Moda Baby e Infantil", "Loja de moda infantil", "roupas infantis", "moda bebê", "vestuário infantil", "loja de roupas"] },
    { "id": 208, "name": "DL Kids", "category": "👶 Loja de moda infantil", "link": "https://share.google/B4o92LFxO3wtd1UuL", "keywords": ["DL Kids", "Loja de moda infantil", "roupas infantis", "moda bebê", "vestuário infantil", "loja de roupas"] },
    { "id": 209, "name": "Bruno Ink Estúdio de Tatuagem", "category": "🎨 Estúdio de tatuagem e colocação de piercing", "link": "https://g.co/kgs/YJNTM97", "keywords": ["Bruno Ink Estúdio de Tatuagem", "Estúdio de tatuagem e colocação de piercing", "tatuagem", "body art", "arte corporal", "tatuador"] },
    { "id": 210, "name": "Vip Motos", "category": "🏍️ Oficina e Peças para Motocicletas", "link": "https://share.google/64WnunOuZQ5UYDr6Y", "keywords": ["Vip Motos", "Oficina e Peças para Motocicletas", "oficina de moto", "peças de moto", "conserto de moto", "manutenção de motos"] },
    { "id": 211, "name": "Zezinho Pneus", "category": "🛠️ Mecânica para Carros", "link": "https://share.google/A1wcNSjLKEE4roWml", "keywords": ["Zezinho Pneus", "Mecânica para Carros", "mecânica automotiva", "pneus", "manutenção veicular", "serviços automotivos"] },
    { "id": 212, "name": "Peixaria do Julinho", "category": "🐟 Peixaria", "link": "https://g.co/kgs/hWyj91C", "keywords": ["Peixaria do Julinho", "Peixaria", "peixe", "frutos do mar", "alimentos", "comida"] },
    { "id": 213, "name": "Dra Lilian Quintanilha", "category": "🦷 Dentista", "link": "https://share.google/64WnunOuZQ5UYDr6Y", "keywords": ["Dra Lilian Quintanilha", "Dentista", "clínica odontológica", "tratamento dentário", "saúde bucal", "odontologia"] },
    { "id": 214, "name": "Barman Up - Open Bar", "category": "🍹 Bar", "link": "https://share.google/7GCT58vw7cTag2Vkj", "keywords": ["Barman Up - Open Bar", "Bar", "open bar", "bartender", "eventos", "drinks", "bar para festas"] },
    { "id": 215, "name": "J&J Produtos de Limpeza", "category": "🧼 Fornecedor de produtos de limpeza", "link": "https://share.google/2402yxA0l2Wh4awKN", "keywords": ["J&J Produtos de Limpeza", "Fornecedor de produtos de limpeza", "produtos de limpeza", "distribuidora de limpeza", "higiene", "produtos para casa"] },
    { "id": 216, "name": "Serralheria do Paulista", "category": "🪓 Serralheria", "link": "https://share.google/3rT7BbjBH7Ear2O4E", "keywords": ["Serralheria do Paulista", "Serralheria", "portões", "grades", "estrutura metálica", "serralheiro"] },
    { "id": 217, "name": "Estúdio Andreza Ramos Fotografia", "category": "📸 Estúdio de fotografia", "link": "https://share.google/Av0s7ZQj3k9yPQy0J", "keywords": ["Estúdio Andreza Ramos Fotografia", "Estúdio de fotografia", "fotografia profissional", "ensaio fotográfico", "eventos", "fotógrafo"] },
    { "id": 218, "name": "2 Reis Odonto", "category": "🦷 Clínica odontológica", "link": "https://share.google/eil46Pw5IE2cjojrt", "keywords": ["2 Reis Odonto", "Clínica odontológica", "Dentistas", "tratamento dentário", "saúde bucal", "dentista"] },
    { "id": 219, "name": "Cafeteria Flor de Café", "category": "☕ Cafeteria", "link": "https://share.google/GWNAfKJW4TB3CkkYz", "keywords": ["Cafeteria Flor de Café", "Cafeteria", "café especial", "lanches", "doces", "café da tarde"] },
    { "id": 220, "name": "Russo Radiadores", "category": "🚗 Oficina Mecânica", "link": "https://share.google/sZusCa8AhFGQ1l3V1", "keywords": ["Russo Radiadores", "Oficina Mecânica", "radiadores", "arrefecimento", "manutenção automotiva", "mecânico"] },
    { "id": 221, "name": "Açaí Campo Grande", "category": "🍧 Loja de açaí", "link": "https://share.google/HHkuKpz0XfBglsOu0", "keywords": ["Açaí Campo Grande", "Loja de açaí", "açaí na tigela", "sobremesa", "lanches", "açaí delivery"] },
    { "id": 222, "name": "Moto Master | Motos Elétricas Bicicletas Elétricas | Campo Grande", "category": "🛵 Concessionária de ciclomotores", "link": "https://share.google/9hC2ED1DVd2x69HEQ", "keywords": ["Moto Master", "Concessionária de ciclomotores", "motos elétricas", "bicicletas elétricas", "mobilidade elétrica", "loja de motos"] },
    { "id": 223, "name": "Pizzaria Ideal.com", "category": "🍕 Pizzaria", "link": "https://share.google/29zASnjGxsqrt3Gmk", "keywords": ["Pizzaria Ideal.com", "Pizzaria", "pizza delivery", "massa artesanal", "restaurante", "pizza perto de mim"] },
    { "id": 224, "name": "CIMC IMOBILIÁRIA", "category": "🏠 Imobiliária", "link": "https://share.google/9MVCsRUcRdNApEJb4", "keywords": ["CIMC IMOBILIÁRIA", "Imobiliária", "compra e venda de imóveis", "aluguel", "corretagem", "imóveis"] },
    { "id": 225, "name": "YOGA DOG'X", "category": "🐶 Loja de ração", "link": "https://share.google/y1Hix6Djy9FSufmvj", "keywords": ["YOGA DOG'X", "Loja de ração", "ração para cães", "alimentos pet", "pet shop", "ração"] },
    { "id": 226, "name": "Paulinho da Ração", "category": "🐶 Pet Shop", "link": "https://share.google/MjN2s5c06qoLqXthn", "keywords": ["Paulinho da Ração", "Pet Shop", "ração animal", "acessórios pet", "banho e tosa", "loja pet"] },
    { "id": 227, "name": "Rio Pragas", "category": "🦟 Dedetizadora", "link": "https://share.google/MudeqXN9pMQMQJ8Ez", "keywords": ["Rio Pragas", "Dedetizadora", "controle de pragas", "desinsetização", "descupinização", "dedetização"] },
    { "id": 228, "name": "Corretor Imobiliário", "category": "🏠 Corretora", "link": "https://share.google/VPbkPSTOsyvK65lCR", "keywords": ["Corretor Imobiliário", "Corretora", "venda de imóveis", "consultoria imobiliária", "aluguel", "corretor de imóveis"] },
    { "id": 229, "name": "Palácio dos Pets", "category": "🐶 Pet Shop", "link": "https://share.google/3DV5Td9jDIYC9gVjH", "keywords": ["Palácio dos Pets", "Pet Shop", "ração animal", "acessórios pet", "banho e tosa", "loja pet"] },
    { "id": 230, "name": "Spa Body Massage", "category": "💇‍♀️ Salão de beleza", "link": "https://share.google/ayCZHx6FDkIblm5Fn", "keywords": ["Spa Body Massage", "Salão de beleza", "massagem", "estética corporal", "bem-estar", "clínica de estética"] },
    { "id": 231, "name": "Instituo Vitallis", "category": "💇‍♀️ Salão de beleza", "link": "https://share.google/9igCZdDwRGpfEuBkP", "keywords": ["Instituo Vitallis", "Salão de beleza", "estética avançada", "tratamentos corporais", "bem-estar", "clínica de estética"] },
    { "id": 232, "name": "Dino Piscinas Sepetiba", "category": "🏊 Loja de produtos para piscinas", "link": "https://share.google/vnR92JA8XzxWvHX6n", "keywords": ["Dino Piscinas Sepetiba", "Loja de produtos para piscinas", "manutenção de piscina", "acessórios para piscina", "limpeza de piscina", "produtos para piscina"] },
    { "id": 233, "name": "Gil Pneus", "category": "🚗 Oficina Mecânica", "link": "https://maps.app.goo.gl/5jmQ15s4mPwXGNsbA", "keywords": ["Gil Pneus", "Oficina Mecânica", "troca de pneus", "alinhamento", "balanceamento", "mecânico"] },
    { "id": 234, "name": "Dra Bruna Ottan", "category": "🦷 Clínica odontológica", "link": "https://share.google/u9hZxVN8c3CLNB6XY", "keywords": ["Dra Bruna Ottan", "Clínica odontológica", "Dentistas", "tratamento dentário", "saúde bucal", "dentista"] },
    { "id": 235, "name": "Odonto Campos (Nova Sepetiba)", "category": "🦷 Clínica odontológica", "link": "https://share.google/DrjkrHGqtyb9Ey9ow", "keywords": ["Odonto Campos", "Clínica odontológica", "Dentistas", "tratamento dentário", "saúde bucal", "dentista"] },
    { "id": 236, "name": "Eu Rio Odonto", "category": "🦷 Clínica odontológica", "link": "https://share.google/rCkZNwu7bUpi3g0Ur", "keywords": ["Eu Rio Odonto", "Clínica odontológica", "Dentistas", "tratamento dentário", "saúde bucal", "dentista"] },
    { "id": 237, "name": "Franquia Moto-Peças/RR Moto-Peças", "category": "🛵 Loja de peças para motocicletas", "link": "https://share.google/6e8xIdiemTcbzcdia", "keywords": ["RR Moto-Peças", "Loja de peças para motocicletas", "peças de moto", "acessórios para moto", "oficina de moto", "moto peças"] },
    { "id": 238, "name": "ANTARES MOTO PEÇAS", "category": "🛵 Loja de peças para motocicletas", "link": "https://share.google/qOEHkGjFwcnOZtlnM", "keywords": ["ANTARES MOTO PEÇAS", "Loja de peças para motocicletas", "peças de moto", "acessórios para moto", "oficina de moto", "moto peças"] },
    { "id": 239, "name": "TMJ Group", "category": "🏢 Serviço B2B", "link": "https://share.google/vhngvIHjFDNEHOBW2", "keywords": ["TMJ Group", "Serviço B2B", "consultoria empresarial", "prestação de serviços", "gestão empresarial", "empresa para empresa"] },
    { "id": 240, "name": "Elisangela Silva Estética Avançada", "category": "💇‍♀️ Salão de beleza", "link": "https://share.google/YiRkL0yfK1WXnYgEa", "keywords": ["Elisangela Silva Estética Avançada", "Salão de beleza", "estética avançada", "tratamentos faciais", "beleza", "clínica de estética"] },
    { "id": 241, "name": "Borboleta Chic", "category": "💇‍♀️ Salão de beleza", "link": "https://share.google/YoTdZt5r5MWfC39a7", "keywords": ["Borboleta Chic", "Salão de beleza", "corte de cabelo", "escova", "colorimetria", "cabeleireiro"] },
    { "id": 242, "name": "Carlos Chaveiro", "category": "🔑 Chaveiro", "link": "https://share.google/8dtkZekuGb6jhFn5A", "keywords": ["Carlos Chaveiro", "Chaveiro", "cópia de chave", "abertura de portas", "chave automotiva", "chaveiro 24h"] },
    { "id": 243, "name": "RF Decor", "category": "🏠 Decorador de interiores", "link": "https://share.google/CuC1urR2Kv6lYCVwt", "keywords": ["RF Decor", "Decorador de interiores", "design de interiores", "projetos residenciais", "decoração", "decorador"] },
    { "id": 244, "name": "Amendoeira Shopping", "category": "🧱 Material de Construção", "link": "https://share.google/0UELqyQLhNgne7mOw", "keywords": ["Amendoeira Shopping", "Material de Construção", "material de obra", "reforma", "construção", "loja de material"] },
    { "id": 245, "name": "Manoela Gil Advocacia e Consultoria em Saúde", "category": "⚖️ Escritório de advocacia", "link": "https://share.google/6c1R1sR5ijn6DqcHu", "keywords": ["Manoela Gil Advocacia", "Escritório de advocacia", "direito à saúde", "consultoria jurídica", "advocacia especializada", "advogado"] },
    { "id": 246, "name": "Cleide Bellas Studio Academy", "category": "💇‍♀️ Salão de beleza", "link": "https://share.google/W72cbil3QV0bCfaeX", "keywords": ["Cleide Bellas Studio Academy", "Salão de beleza", "cursos de beleza", "cabeleireiro", "estética", "salão"] },
    { "id": 247, "name": "Escritório Oliveira & Rizzi Advogados Especializados", "category": "⚖️ Assistência jurídica", "link": "https://share.google/JDb9AWhQF0xWxD6do", "keywords": ["Oliveira & Rizzi Advogados", "Assistência jurídica", "consultoria jurídica", "direito civil", "advocacia", "advogado"] },
    { "id": 248, "name": "2 Irmãos Moto Peças | Paciência", "category": "🏍️ Loja de motocicletas", "link": "https://share.google/JpEIQDNu9wpeNNmeY", "keywords": ["2 Irmãos Moto Peças", "Loja de motocicletas", "motos", "peças de moto", "acessórios", "moto peças"] },
    { "id": 249, "name": "Nova Maps Material de Construção", "category": "⚡️ Loja de materiais elétricos", "link": "https://share.google/37dn0MMSfGkIkrRnh", "keywords": ["Nova Maps Material de Construção", "Loja de materiais elétricos", "material elétrico", "instalação elétrica", "iluminação", "loja elétrica"] },
    { "id": 250, "name": "Ferreira Veículos", "category": "🚗 Concessionária", "link": "https://share.google/93Aay62pi3IyTbDYQ", "keywords": ["Ferreira Veículos", "Concessionária", "compra e venda de carros", "veículos seminovos", "automóveis", "loja de carros"] },
    { "id": 251, "name": "Corcel Azul Centro Automotivo", "category": "🚗 Oficina Mecânica", "link": "https://share.google/07zbD9cYnyTeAtOPt", "keywords": ["Corcel Azul Centro Automotivo", "Oficina Mecânica", "manutenção automotiva", "revisão de carro", "mecânico", "mecânica"] },
    { "id": 252, "name": "Nova Maps Materiais de Construção", "category": "⚡️ Loja de materiais elétricos", "link": "https://share.google/8ROoaVRMDqKMQ5xeV", "keywords": ["Nova Maps Materiais de Construção", "Loja de materiais elétricos", "material elétrico", "instalação elétrica", "iluminação", "loja elétrica"] },
    { "id": 253, "name": "Foca no Bistrô", "category": "🍻 Bar", "link": "https://share.google/S0dZZAKvfSo9WfJF2", "keywords": ["Foca no Bistrô", "Bar", "bistrô", "chopp artesanal", "petiscos", "barzinho"] },
    { "id": 254, "name": "Ótica Vila Nova", "category": "👓 Ótica", "link": "https://share.google/fxI2XBgfr51i5Qv9K", "keywords": ["Ótica Vila Nova", "Ótica", "óculos", "lentes", "exame de vista", "ótica"] },
    { "id": 255, "name": "Auto Center do Gugu", "category": "🚗 Oficina Mecânica", "link": "https://share.google/jcSh5bkmrEFPoD9jo", "keywords": ["Auto Center do Gugu", "Oficina Mecânica", "manutenção automotiva", "revisão de carro", "mecânico", "mecânica"] },
    { "id": 256, "name": "Dinah Gás - Distribuidora", "category": "⛽ Companhia de Gás", "link": "https://share.google/sYswp31d1uYJ82hd2", "keywords": ["Dinah Gás - Distribuidora", "Companhia de Gás", "gás", "entrega de gás", "botijão", "gás perto de mim"] },

    { "id": 257, "name": "IdealFrio RJ - Refrigeração e climatização", "category": "❄️ Loja de refrigeradores", "link": "https://share.google/IIdoTl9NjaB9h3k62", "keywords": ["IdealFrio RJ - Refrigeração e climatização", "Loja de refrigeradores", "ar condicionado", "refrigeração", "instalação de ar", "conserto de ar"] },

    { "id": 258, "name": "WG casa de ração e PetShop", "category": "🐶 Pet Shop", "link": "https://share.google/d657zB5yhncu1tPIf", "keywords": ["WG casa de ração e PetShop", "Pet Shop", "ração", "ração para cães", "acessórios pet", "pet shop"] },

    { "id": 259, "name": "Rancho Pousada Diná e Miranda", "category": "🏡 Pousada", "link": "https://share.google/tuEbr3vtmQWfEgHSG", "keywords": ["Rancho Pousada Diná e Miranda", "Pousada", "hospedagem", "pousada com lazer", "fim de semana", "pousada"] },

    { "id": 260, "name": "Ferreira e Souza Odontologia", "category": "🦷 Dentista", "link": "https://share.google/dU7NPWuhUtZmmjjsr", "keywords": ["Ferreira e Souza Odontologia", "Dentista", "clínica odontológica", "Dentistas", "tratamento dentário", "dentista"] },

    { "id": 261, "name": "RN Artes Sublimação", "category": "🖨️ Gráfica", "link": "https://share.google/DTQfvSOzDribVGpga", "keywords": ["RN Artes Sublimação", "Gráfica", "sublimação", "camisas personalizadas", "impressão", "gráfica rápida"] },

    { "id": 262, "name": "Império das Motos Elétricas", "category": "🛵 Concessionária de ciclomotores", "link": "https://share.google/mYUGPWKVKEwrxi27T", "keywords": ["Império das Motos Elétricas", "Concessionária de ciclomotores", "moto elétrica", "scooter elétrica", "mobilidade elétrica", "loja de motos"] },

    { "id": 263, "name": "Kaizen Soluções Imobiliária", "category": "🏠 Imobiliária", "link": "https://share.google/46UTsyfgNjDbaApzE", "keywords": ["Kaizen Soluções Imobiliária", "Imobiliária", "aluguel", "compra e venda", "corretor de imóveis", "imóveis"] },

    { "id": 264, "name": "Auto Escola Campinho", "category": "🚗 Auto Escola", "link": "https://share.google/RSzoIlwQSebsH8olg", "keywords": ["Auto Escola Campinho", "Auto Escola", "habilitação", "aulas de direção", "CNH", "auto escola"] },

    { "id": 265, "name": "Raquel Mendes", "category": "⚖️ Advogado", "link": "https://share.google/FFQKb9gVEeUquJTYa", "keywords": ["Raquel Mendes", "Advogado", "consultoria jurídica", "processo", "direito", "advogado"] },

    { "id": 266, "name": "Família Gesso", "category": "🧱 Loja de materiais para paredes de gesso", "link": "https://share.google/nksgV2JfSV3Vt6bvy", "keywords": ["Família Gesso", "Loja de materiais para paredes de gesso", "drywall", "forro de gesso", "divisória", "gesso"] },

    { "id": 267, "name": "Boutique Ana Flor", "category": "👗 Loja de roupa", "link": "https://share.google/dRiUe7rckCb1xlgAL", "keywords": ["Boutique Ana Flor", "Loja de roupa", "moda feminina", "vestuário", "looks", "roupa"] },

    { "id": 268, "name": "Total Cred Cg - Emprestimo", "category": "💰 Agência de empréstimos", "link": "https://share.google/ZA5mb0qG644R5y73b", "keywords": ["Total Cred Cg - Emprestimo", "Agência de empréstimos", "crédito", "empréstimo pessoal", "consignado", "empréstimo"] },

    { "id": 269, "name": "Dental Clean Santa Cruz", "category": "🦷 Dentista", "link": "https://share.google/uHesYMYCShPFzM6q6", "keywords": ["Dental Clean Santa Cruz", "Dentista", "clínica odontológica", "Dentistas", "tratamento dentário", "dentista"] },

    { "id": 270, "name": "Inovar Imóveis", "category": "🏠 Imobiliária", "link": "https://share.google/0qmiYhGoLM43m0uRw", "keywords": ["Inovar Imóveis", "Imobiliária", "aluguel", "compra e venda", "corretagem", "imóveis"] },

    { "id": 271, "name": "Vergalhão", "category": "🛠️ Loja de Ferragens", "link": "https://share.google/kQkf49btzcY0Z31sE", "keywords": ["Vergalhão", "Loja de Ferragens", "ferragens", "vergalhão", "obra", "material de construção"] },

    { "id": 272, "name": "Era do Gelo Distribuidora de Bebidas", "category": "🍾 Distribuidor de Bebidas", "link": "https://share.google/wuwcn7VEoMNMrKObm", "keywords": ["Era do Gelo Distribuidora de Bebidas", "Distribuidor de Bebidas", "bebidas", "gelo", "entrega", "distribuidora"] },

    { "id": 273, "name": "Furacão Auto e Moto Peças", "category": "🚗 Loja de autopeças", "link": "https://share.google/ymRGerZLHKbipcwan", "keywords": ["Furacão Auto e Moto Peças", "Loja de autopeças", "peças automotivas", "peças de moto", "acessórios", "auto peças"] },

    { "id": 274, "name": "Lourival Junior Consultoria e Advocacia", "category": "📊 Consultoria", "link": "https://share.google/NNFhk1AXxW1UiJrEY", "keywords": ["Lourival Junior Consultoria e Advocacia", "Consultoria", "assessoria", "consultoria jurídica", "orientação", "consultor"] },

    { "id": 275, "name": "Pet Shop Cãompo Grande", "category": "🐶 Pet Shop", "link": "https://share.google/oOcTTYRcju0EKIkha", "keywords": ["Pet Shop Cãompo Grande", "Pet Shop", "ração", "banho e tosa", "acessórios pet", "pet shop"] },

    { "id": 276, "name": "Advogados Gomes e Pimentel (Campo Grande)", "category": "⚖️ Escritório de advocacia", "link": "https://share.google/yCg8W1Bj1qsBDDp4Z", "keywords": ["Advogados Gomes e Pimentel (Campo Grande)", "Escritório de advocacia", "consultoria jurídica", "processo", "direito", "advogado"] },

    { "id": 277, "name": "Instituto Deluniize Santos - Saúde Integrativa e estética avançada", "category": "💇‍♀️ Salão de beleza", "link": "https://share.google/evFN4TSHXF7Wkgjkq", "keywords": ["Instituto Deluniize Santos - Saúde Integrativa e estética avançada", "Salão de beleza", "estética avançada", "tratamentos", "bem-estar", "estética"] },

    { "id": 278, "name": "Instituto Deluniize Santos Saúde e Estética | Clínica de Estética na Barra da Tijuca", "category": "💇‍♀️ Salão de beleza", "link": "https://share.google/Ep3zrp9oMGFzTDabB", "keywords": ["Instituto Deluniize Santos Saúde e Estética", "Salão de beleza", "clínica de estética", "tratamentos corporais", "beleza", "estética"] },

    { "id": 279, "name": "Pierre Silva Advogado Trabalhista", "category": "⚖️ Advogado trabalhista", "link": "https://share.google/EZHUDfIR8fx7ZTP5L", "keywords": ["Pierre Silva Advogado Trabalhista", "Advogado trabalhista", "direitos trabalhistas", "rescisão", "ação trabalhista", "advogado"] },

    { "id": 280, "name": "Nohana Quintanilha Advocacia", "category": "⚖️ Escritório de advocacia", "link": "https://share.google/8TvkGTU8Nj6SH48kU", "keywords": ["Nohana Quintanilha Advocacia", "Escritório de advocacia", "consultoria jurídica", "processo", "direito", "advogado"] },

    { "id": 281, "name": "OdontoCampos", "category": "🦷 Clínica odontológica", "link": "https://share.google/viAQ5vPPcznEIszjp", "keywords": ["OdontoCampos", "Clínica odontológica", "Dentistas", "tratamento dentário", "saúde bucal", "dentista"] },

    { "id": 282, "name": "Luanda Naiara Advogada (Concurso Público)", "category": "⚖️ Advogado", "link": "https://share.google/fslAsBAmSB34s0cGw", "keywords": ["Luanda Naiara Advogada (Concurso Público)", "Advogado", "concurso público", "direito administrativo", "consultoria jurídica", "advogado"] },

    { "id": 283, "name": "Murilo Jóias", "category": "💍 Joalheria", "link": "https://share.google/LDXydtosxglFffFfI", "keywords": ["Murilo Jóias", "Joalheria", "joias", "alianças", "ouro", "joalheria"] },

    { "id": 284, "name": "Copy Speed / CS Print", "category": "🖨️ Copiadora", "link": "https://share.google/UJSFItschcFbfIRuw", "keywords": ["Copy Speed / CS Print", "Copiadora", "xerox", "impressão", "encadernação", "cópias"] },

    { "id": 285, "name": "Dra Maíres | Advocacia | Advogada em Campo Grande", "category": "⚖️ Escritório de advocacia", "link": "https://share.google/AhBQ7zyknfJdSlVhv", "keywords": ["Dra Maíres | Advocacia | Advogada em Campo Grande", "Escritório de advocacia", "consultoria jurídica", "direito", "processo", "advogado"] },

    { "id": 286, "name": "In Loco Imóveis", "category": "🏠 Imobiliária", "link": "https://share.google/2yovGDYolXk3biYMx", "keywords": ["In Loco Imóveis", "Imobiliária", "aluguel", "compra e venda", "corretagem", "imóveis"] },

    { "id": 287, "name": "Autocenter Montana", "category": "🚗 Oficina Mecânica", "link": "https://share.google/7DFBTT21kQy5G18D0", "keywords": ["Autocenter Montana", "Oficina Mecânica", "auto center", "manutenção automotiva", "revisão", "mecânica"] },

    { "id": 288, "name": "Dra Patrícia Croucillo CRORJ 57950 / Consultorio odontológico / Cirurgiã - Dentista / Freguesia e Campo Grande", "category": "🦷 Clínica odontológica", "link": "https://share.google/y5a1xLuEQfrI6Gjw9", "keywords": ["Dra Patrícia Croucillo", "Clínica odontológica", "Dentistas", "cirurgião dentista", "tratamento dentário", "dentista"] },

    { "id": 289, "name": "Shop Motocar Centro Automotivo", "category": "🚗 Oficina Mecânica", "link": "https://share.google/FukX2DboNMQjCOgCc", "keywords": ["Shop Motocar Centro Automotivo", "Oficina Mecânica", "auto center", "manutenção automotiva", "revisão", "mecânica"] },

    { "id": 290, "name": "Policar’los | Estética automotiva | Serviços automotivos em Campo Grande", "category": "🚘 Estética automotiva", "link": "https://share.google/7ADou6YTaGbgSZWIe", "keywords": ["Policar’los | Estética automotiva", "Estética automotiva", "lavagem detalhada", "higienização interna", "polimento", "lavagem de carro"] },

    { "id": 291, "name": "M BROTHER MOTORS", "category": "🛵 Concessionária de motos elétricas", "link": "https://share.google/7PnkjxEj7za46aCSE", "keywords": ["M BROTHER MOTORS", "Concessionária de motos elétricas", "moto elétrica", "scooter elétrica", "mobilidade elétrica", "loja de motos"] },

    { "id": 292, "name": "Queiroz Santos Advogados - Campo Grande Rio de Janeiro - RJ", "category": "⚖️ Escritório de advocacia", "link": "https://share.google/EDshxi5vPfz65tu8T", "keywords": ["Queiroz Santos Advogados", "Escritório de advocacia", "consultoria jurídica", "direito", "processo", "advogado"] },

    { "id": 293, "name": "Canuto Piscinas - Loja de produtos para piscinas", "category": "🏊 Loja de produtos para piscinas", "link": "https://share.google/Uf8vv3dt1ovRF68km", "keywords": ["Canuto Piscinas", "Loja de produtos para piscinas", "limpeza de piscina", "manutenção de piscina", "acessórios", "produtos para piscina"] },

    { "id": 294, "name": "Luci-Luci | Perfumaria Fina", "category": "🧴 Perfumaria", "link": "https://share.google/g5dBrpofPMyatttKh", "keywords": ["Luci-Luci | Perfumaria Fina", "Perfumaria", "perfumes importados", "cosméticos", "presentes", "perfume"] },

    { "id": 295, "name": "Rei das Motos Elétricas - Km 32", "category": "🛵 Concessionária de motos elétricas", "link": "https://share.google/aquIEFuy3XBoowINa", "keywords": ["Rei das Motos Elétricas - Km 32", "Concessionária de motos elétricas", "moto elétrica", "scooter elétrica", "mobilidade elétrica", "loja de motos"] },

    { "id": 296, "name": "Virtuosa", "category": "💄 Loja de produtos de beleza", "link": "https://share.google/bJdjCr42ZWdhkcYnp", "keywords": ["Virtuosa", "Loja de produtos de beleza", "maquiagem", "skincare", "cosméticos", "produtos de beleza"] },

    { "id": 297, "name": "MN Centro Automotivo", "category": "🚘 Estética automotiva", "link": "https://share.google/yCvktrSSp1CGigi3Z", "keywords": ["MN Centro Automotivo", "Estética automotiva", "lavagem detalhada", "higienização interna", "polimento", "lavagem de carro"] },

    { "id": 298, "name": "J&R Consertos De Eletrodomésticos", "category": "🔧 Conserto de eletrodomésticos", "link": "https://share.google/AHdCfrJwt2VrN60ft", "keywords": ["J&R Consertos De Eletrodomésticos", "Conserto de eletrodomésticos", "assistência técnica", "geladeira", "máquina de lavar", "conserto"] },

    { "id": 299, "name": "Bazar j&r consertos", "category": "🔧 Conserto de eletrodomésticos", "link": "https://share.google/IFT7IjpR4m7tjSAdE", "keywords": ["Bazar j&r consertos", "Conserto de eletrodomésticos", "assistência técnica", "micro-ondas", "ventilador", "conserto"] },

    { "id": 300, "name": "Odonto Campos (Sepetiba)", "category": "🦷 Clínica odontológica", "link": "https://share.google/h26NRp0Sape1E66xB", "keywords": ["Odonto Campos (Sepetiba)", "Clínica odontológica", "Dentistas", "tratamento dentário", "saúde bucal", "dentista"] },

    { "id": 301, "name": "Joice Lopes", "category": "⚖️ Escritório de advocacia", "link": "https://share.google/9dKC8DrECxFi7Iglr", "keywords": ["Joice Lopes", "Escritório de advocacia", "consultoria jurídica", "direito", "processo", "advogado"] },

    { "id": 302, "name": "Luanda Advocacia Previdenciário", "category": "⚖️ Advogado previdenciário", "link": "https://share.google/RQCn1mqiuOgB6l3hp", "keywords": ["Luanda Advocacia Previdenciário", "Advogado previdenciário", "aposentadoria", "INSS", "benefícios", "advogado"] },

    { "id": 303, "name": "Dra Leila Ferreira Quintanilha de Souza", "category": "👂 Otorrinolaringologista", "link": "https://share.google/PsxZo2CQdNUXRqbVj", "keywords": ["Dra Leila Ferreira Quintanilha de Souza", "Otorrinolaringologista", "otorrino", "nariz", "garganta", "ouvido"] },

    { "id": 304, "name": "Optimacar Nacionais e Importados auto center", "category": "🚗 Oficina Mecânica", "link": "https://share.google/5XR53tWsecIVJYkZE", "keywords": ["Optimacar Nacionais e Importados auto center", "Oficina Mecânica", "auto center", "revisão", "manutenção automotiva", "mecânica"] },

    { "id": 305, "name": "Família dos Pets | Pet shop em Campo Grande", "category": "🐶 Pet Shop", "link": "https://share.google/cRsvTs1lT5BP85hid", "keywords": ["Família dos Pets | Pet shop em Campo Grande", "Pet Shop", "ração", "banho e tosa", "acessórios pet", "pet shop"] },

    { "id": 306, "name": "Espaço MiBela", "category": "💇‍♀️ Salão de beleza", "link": "https://share.google/rJLK7mVqGQQyBjGwB", "keywords": ["Espaço MiBela", "Salão de beleza", "corte de cabelo", "escova", "beleza", "salão"] },

    { "id": 307, "name": "C. Car Premiun", "category": "🚗 Concessionária", "link": "https://share.google/F8MwOTSrTe64zYhw6", "keywords": ["C. Car Premiun", "Concessionária", "loja de carros", "seminovos", "compra e venda", "carros"] },

    { "id": 308, "name": "Inova Pet Campo Grande", "category": "🐶 Pet Shop", "link": "https://share.google/ji77CDtuPFqBIdRLI", "keywords": ["Inova Pet Campo Grande", "Pet Shop", "ração", "banho e tosa", "acessórios pet", "pet shop"] },

    { "id": 309, "name": "Bistrô Show de Sabor", "category": "🍽️ Restaurante", "link": "https://share.google/268jxifTYA8lJPUQN", "keywords": ["Bistrô Show de Sabor", "Restaurante", "comida caseira", "almoço", "jantar", "restaurante"] },

    { "id": 310, "name": "Luz do Mundo: A Sua Loja de Elétrica", "category": "🧱 Loja de materiais de construção", "link": "https://share.google/ovBAv87VQ6WyoOSDw", "keywords": ["Luz do Mundo: A Sua Loja de Elétrica", "Loja de materiais de construção", "material elétrico", "instalação elétrica", "iluminação", "loja de elétrica"] },

    { "id": 311, "name": "Autocenter Montana", "category": "🚗 Oficina Mecânica", "link": "https://share.google/Y62K3bbvcZkL0srW8", "keywords": ["Autocenter Montana", "Oficina Mecânica", "auto center", "manutenção automotiva", "revisão", "mecânica"] },

    { "id": 312, "name": "Pop Gastronomia- Café e Refeição", "category": "☕ Cafeteria", "link": "https://share.google/rHqc7FKznxi2EyX1z", "keywords": ["Pop Gastronomia- Café e Refeição", "Cafeteria", "café", "refeições", "almoço", "café da manhã"] },

    { "id": 313, "name": "Sítio do Juca", "category": "🎉 Salão de festas", "link": "https://share.google/2RDnT7ByKfIHZAlpf", "keywords": ["Sítio do Juca", "Salão de festas", "festa", "evento", "casamento", "salão para festas"] },

    { "id": 314, "name": "Gesso Mix", "category": "🧱 Loja de materiais para paredes de gesso", "link": "https://share.google/9bqky5NREnZhtYp2k", "keywords": ["Gesso Mix", "Loja de materiais para paredes de gesso", "drywall", "forro de gesso", "divisória", "gesso"] },

    { "id": 315, "name": "Psicólogo Flávio Soares", "category": "🧠 Psicólogo", "link": "https://share.google/zDxvjm04RdA65z45p", "keywords": ["Psicólogo Flávio Soares", "Psicólogo", "terapia", "psicoterapia", "ansiedade", "psicólogo"] },

    { "id": 316, "name": "Lidiane Pescados", "category": "🐟 Peixaria", "link": "https://share.google/0t2Zs7qUylpaMFXFD", "keywords": ["Lidiane Pescados", "Peixaria", "pescados", "frutos do mar", "peixe fresco", "peixaria"] },

    { "id": 317, "name": "Bike Eletric Rio", "category": "🛵 Concessionária de motos elétricas", "link": "https://share.google/DPCr7s0Xl3GV1Fy2A", "keywords": ["Bike Eletric Rio", "Concessionária de motos elétricas", "moto elétrica", "bike elétrica", "mobilidade elétrica", "loja de motos"] },

    { "id": 318, "name": "Batista e Calzolari Advogados Associados", "category": "⚖️ Escritório de advocacia", "link": "https://share.google/fLE3I0WP7v7wOAlsb", "keywords": ["Batista e Calzolari Advogados Associados", "Escritório de advocacia", "consultoria jurídica", "direito", "processo", "advogado"] },

    { "id": 319, "name": "Sabor da Hora Restaurante", "category": "🍽️ Restaurante", "link": "https://share.google/TytU9CgvcFOMyL5lN", "keywords": ["Sabor da Hora Restaurante", "Restaurante", "comida caseira", "almoço", "jantar", "restaurante"] },

    { "id": 320, "name": "Auto Peças Auto Car Parts", "category": "🚗 Loja de autopeças", "link": "https://share.google/XHBxPwAuLUfM8A5uA", "keywords": ["Auto Peças Auto Car Parts", "Loja de autopeças", "auto peças", "peças automotivas", "acessórios", "peças de carro"] },

    { "id": 321, "name": "Comendador Joias | Joalheria | Campo Grande-RJ", "category": "💍 Joalheria", "link": "https://share.google/G6mxd5kUifvtyhvIJ", "keywords": ["Comendador Joias | Joalheria | Campo Grande-RJ", "Joalheria", "alianças", "ouro", "presente", "joias"] },

    { "id": 322, "name": "Imobiliária Zion", "category": "🏠 Imobiliária", "link": "https://share.google/Q1FDa9xikgMqPs1It", "keywords": ["Imobiliária Zion", "Imobiliária", "aluguel", "compra e venda", "corretor de imóveis", "imóveis"] },

    { "id": 323, "name": "Vertical Adventure", "category": "🧗 Agência de Turismo Esportivo", "link": "https://share.google/90r5aucXsigQRfWMx", "keywords": ["Vertical Adventure", "Agência de Turismo Esportivo", "turismo de aventura", "trilhas", "escalada", "passeios"] },

    { "id": 324, "name": "Mega Elétron - Campo Grande", "category": "⚡ Concessionária de veículos elétricos", "link": "https://share.google/HsJCWWnG3IjeNBe8S", "keywords": ["Mega Elétron - Campo Grande", "Concessionária de veículos elétricos", "veículo elétrico", "carro elétrico", "mobilidade elétrica", "loja de carros"] },

    { "id": 325, "name": "MotoChefe Nova Iguaçu", "category": "🛵 Concessionária de motos elétricas", "link": "https://share.google/LA5UGuKfDwfXkxofG", "keywords": ["MotoChefe Nova Iguaçu", "Concessionária de motos elétricas", "moto elétrica", "scooter elétrica", "mobilidade elétrica", "loja de motos"] },

    { "id": 326, "name": "MOTOCHEFE NILÓPOLIS", "category": "🛵 Concessionária de motos elétricas", "link": "https://share.google/PtM9KsYGKScGWTI6p", "keywords": ["MOTOCHEFE NILÓPOLIS", "Concessionária de motos elétricas", "moto elétrica", "scooter elétrica", "mobilidade elétrica", "loja de motos"] },

    { "id": 327, "name": "Car Pro Serviços Automotivos", "category": "🚗 Oficina Mecânica", "link": "https://share.google/YGjwIcCX7Q54BUlgm", "keywords": ["Car Pro Serviços Automotivos", "Oficina Mecânica", "manutenção automotiva", "revisão", "mecânico", "mecânica"] },

    { "id": 328, "name": "Sanitária Humac Ltda", "category": "🧱 Loja de materiais de construção", "link": "https://share.google/BOfadM3ykYyc6Q8Ul", "keywords": ["Sanitária Humac Ltda", "Loja de materiais de construção", "hidráulica", "tubos e conexões", "obra", "material de construção"] },

    { "id": 329, "name": "Pereira Advocacia", "category": "⚖️ Escritório de advocacia", "link": "https://share.google/HnvudQv3J8w3WPJxV", "keywords": ["Pereira Advocacia", "Escritório de advocacia", "consultoria jurídica", "direito", "processo", "advogado"] },

    { "id": 330, "name": "Lavíparfum Cosméticos e Perfumaria Multimarcas", "category": "🧴 Perfumaria", "link": "https://share.google/jsYOvqsD9cFNRvWdC", "keywords": ["Lavíparfum Cosméticos e Perfumaria Multimarcas", "Perfumaria", "cosméticos", "maquiagem", "presentes", "perfume"] },

    { "id": 331, "name": "FGM advocacia criminal", "category": "⚖️ Advogado criminal", "link": "https://share.google/iW1vFA7KKHVacAkrQ", "keywords": ["FGM advocacia criminal", "Advogado criminal", "defesa criminal", "audiência", "processo criminal", "advogado"] },

    { "id": 332, "name": "Dra. Tatiane Gomes Saúde Estética", "category": "💇‍♀️ Salão de beleza", "link": "https://share.google/ws6hDQfZvyT01boVh", "keywords": ["Dra. Tatiane Gomes Saúde Estética", "Salão de beleza", "estética", "tratamentos", "bem-estar", "clínica de estética"] },

    { "id": 333, "name": "Alonso Produções", "category": "🎙️ Estúdio de gravação", "link": "https://share.google/ZOoUyeqNbNAPxkgNT", "keywords": ["Alonso Produções", "Estúdio de gravação", "gravação", "produção musical", "mixagem", "estúdio"] },

    { "id": 334, "name": "Jorjão Pneus Auto Center", "category": "🛞 Comércio de pneu", "link": "https://share.google/clJChoORjXRlTodP9", "keywords": ["Jorjão Pneus Auto Center", "Comércio de pneu", "pneus", "troca de pneus", "alinhamento", "pneu"] },

    { "id": 335, "name": "Vidraçaria e Marmoraria Art Rio", "category": "🪟 Vidraçaria", "link": "https://share.google/lyozaiNV11YpRiug7", "keywords": ["Vidraçaria e Marmoraria Art Rio", "Vidraçaria", "box vidro", "espelho", "vidros", "vidraceiro"] },

    { "id": 336, "name": "Marosa Imóveis", "category": "🏠 Imobiliária", "link": "https://share.google/xqULdaw8vOYy18tcZ", "keywords": ["Marosa Imóveis", "Imobiliária", "aluguel", "compra e venda", "corretagem", "imóveis"] },

    { "id": 337, "name": "APOSENTADORIA_MPREV", "category": "⚖️ Advogado previdenciário", "link": "https://share.google/t77K02kWJUGiXYnWo", "keywords": ["APOSENTADORIA_MPREV", "Advogado previdenciário", "aposentadoria", "INSS", "benefícios", "advogado"] },

    { "id": 338, "name": "Vidraçaria Santíssimo", "category": "🪟 Vidraçaria", "link": "https://share.google/Kk9On4kypX46qvSFL", "keywords": ["Vidraçaria Santíssimo", "Vidraçaria", "box vidro", "espelho", "vidros", "vidraceiro"] },

    { "id": 339, "name": "Fama Bar e Lounge LTDA", "category": "🍸 Gastropub", "link": "https://share.google/KmCBOlf6BXWP2sndz", "keywords": ["Fama Bar e Lounge LTDA", "Gastropub", "bar", "lounge", "drinks", "barzinho"] }
];